spring:
  profiles:
    active: test   



---     
spring:
    profiles: test
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ecsite
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
server:
  context-path: /ecsite

---     
spring:
    profiles: dev
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecsite
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp


server:
  context-path: /ecsite
